

List<String> facts = [
  'Covid-19 and SARS-CoV-2 are not the same thing. Covid-19 is a disease (D stands for disease) caused by a new coronavirus. SARS-CoV-2 is the name of the virus itself.',
  'Coronaviruses are impostors from biology. The tailpiece of each spike “imitates” the molecule of a useful substance, so that the cellular receptors gladly pull it into themselves, and the whole virus is squeezed into the cell after the spike is in. This is how infection occurs.',
  'Once in a cell, the virus “seizes” control over it and forces it to endlessly produce its own copies - instead of its usual proteins. A chain reaction begins. As a result, the cell dies, but the carrier of the infection becomes contagious.',
  'At the initial stage of infection, the new coronavirus actively reproduces itself in the throat and upper respiratory tract. Then the infection goes down and can reach the lungs, causing inflammation.',
  'The first symptom of infection is a cough. Only then the temperature begins to rise.',
  'Many people who become infected (18% or one in five people) do not even have a cough. The disease proceeds without any symptoms at all: a person may not even suspect that he is sick.',
  'Covid-19 is also treated in the same way as regular flu - at home, symptomatically.',
  'Loss of a sense of taste and/or smell is not a common symptom - is does not necessarily happens in all Covid-19 cases, sometimes it is the only symptom.',
  'The carrier of a new coronavirus becomes dangerous to others immediately after being infected - long before the first symptoms (if any).',
  'The good news: the more deadly a virus is, the worse it is spreading. By killing its master, the virus can no longer infect others. Therefore, the virus rarely mutates into a more deadly form, it is not in its interests.',
  'This virus makes its host a spreader, but it does not appear immediately or does not appear at all, so the carrier manages to infect several more people.',
  'On average, each carrier of a new coronavirus manages to infect 2 to 4 healthy people. This number is higher than seasonal flu (1.3), but lower than measles (12+).',
  'In South Korea, the virus was controlled until the number of cases reached 30. But the woman, codenamed "Patient 31", immediately infected about 1,200 people.',
  'Over 10 days, the number of infected in South Korea increased from 30 to 5,000.',
  'The mortality rate from Covid-19 is still difficult to calculate with accuracy, but most studies estimate it at 1-3%.',
  'Mortality from Covid-19 is highly dependent on the overall burden on the healthcare system and the rapidity of delivery medical care: in Germany it is only 0.3%, in Italy it is almost 9%.',
  'In the age group of 70+, mortality exceeds 5%; 80+, every tenth dies of the virus.',
  'The pandemic is quickly developing: 100,000 patients 67 days after the first diagnosis, the second 100,000 became ill in 11 days, and the third - in 4 days.',
  'Every day, the number of people infected with the virus increases by about a third.',
  'The pandemic has already reached the most remote corners of the globe, including the famous Easter Island, where on March 24, the first patient, a 42-year-old man, was officially confirmed.',
  'It is not exactly known where SARS-CoV-2 came from, but bats and pangolins carry viruses similar to this one.',
  'The virus did not run away from the biological laboratory, no matter how much someone would like to believe it.',
  'Surgical masks DO NOT protect against coronavirus. Its particles are so small that they easily pass through the pores.',
  'Contrary to popular belief, pets can NOT spread the coronavirus. No cases of human infection from a dog or cat have yet been reported.',
  'The virus can be picked up in an absolutely empty room, where the infected had previously been present.',
  'In the air, the coronavirus remains viable (that is, it can infect healthy people) for three hours.',
  'On plastic and steel surfaces, SARS-CoV-2 remains dangerous for up to three days, on paper and cardboard - up to a day, on copper - up to four hours.',
  'The main and most reliable means of prevention is to wash your hands thoroughly after contacting any surfaces outside your home.',
  'If there is no opportunity to wash your hands with soap, use hand gel antiseptic.Fact 52. If there is no opportunity to wash your hands with soap, use hand gel antiseptic.',
  'Lockdown and other restrictive measures may be extended around the world (with short interruptions) until a vaccine or effective treatment for Covid-19 are found.',
  'At the very least, miramistin or chlorhexidine will do for disinfection: they both destroy bacteria and viruses.',
  'Antibiotics against coronavirus are useless. It is absolutely clear that an effective vaccine for coronavirus will NOT appear earlier than in a year - year and a half, by the mid or end of 2021. At this point under the threat are likely to get sick.',
  'The majority of patients (over 80%) do not need medical assistance at all. They treat themselves at home, with the help of ordinary flu, and usually recover in about a week.',
  'Sneezing is NOT a symptom of coronavirus. Coughing - yes, sneezing - no.'
  'SARS-CoV-2 continues mutating. From December to March, some variants of the virus managed to change the genome 14 times.',
];